#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

. scripts/get-env "$@"

(echo "building client"; yarn --cwd client build)

(echo "building shared"; yarn --cwd shared build)

(echo "building server"; yarn --cwd server build)

(echo "copying install info"; cp package.json yarn.lock dist)
