#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

. scripts/get-env "$@"

(echo "loading map styles"; scripts/load-styles)

(echo "building client"; yarn --cwd client build)

(echo "building shared"; yarn --cwd shared build)

(echo "building server"; yarn --cwd server build)

(echo "copying install info"; cp package.json yarn.lock .yarnrc.yml dist; mkdir -p dist/client; cp client/package.json dist/client/)
