#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

. scripts/get-env "$@"

if [ ! -z "$DOTENV_FILE" ]; then
  set -a
  . "$DOTENV_FILE"
  set +a
fi

if [ -z "$DEPLOY_HOST" ]; then
  echo 'DEPLOY_HOST is not set.' >&2
  echo 'Please add this to dist/.env or provide it on the command line.' >&2
  echo >&2
  echo 'To deploy to a specific environment, please use -e / --env,' >&2
  echo 'e.g. "--env prod" to use dist/prod.env,' >&2
  echo 'or "--env -" to use the current branch name.' >&2
  echo >&2
  exit 1
fi

if [ -z "$DEPLOY_USER" ]; then
  DEPLOY_TARGET="$DEPLOY_HOST"
else
  DEPLOY_TARGET="$DEPLOY_USER@$DEPLOY_HOST"
fi

if [ -z "$DEPLOY_KEYPAIR" ]; then
  DEPLOY_FLAG=""
else
  DEPLOY_FLAG="$(printf -- "-i%q" "$DEPLOY_KEYPAIR")"
fi

if [ "$0" = "$BASH_SOURCE" ]; then
  ssh $DEPLOY_FLAG "$DEPLOY_TARGET" "${REST_ARGS[@]}"
fi
